### ISSUE TITLE
How to trace after running mcut?

### ISSUE THREAD

**Issue by feO2x** [LeeSanderson/Chess#1]
Hey Lee,

first of all, thank you so much for putting Chess on GitHub and NuGet! After going through the examples and documentation (online and in Resources/Docs), I still have one question that I couldn't get the answer to: **how can I trace deadlocks or data races when a test in mcut fails?**

Sure, mcut produces the "allResults.xml" and session.tmp folder, but I can't feed them to the Concurrency Explorer or mchess with attached debugger. Both of them require a trace file, and I don't think that there are any switches for mcut to produce these traces while executing the tests.

Thanks for your help in advance.

**Comment by LeeSanderson** [comment]
I run mcut as part of my build to ensure that I don't have any concurrency regressions.

Diagnosing the cause of deadlocks and data races can be tricky. The output from mcut might give you some hints or you can use [Alpaca](https://github.com/LeeSanderson/Chess/tree/master/ConcurrencyTools/Alpaca). For now you will have to build Alpaca by cloning the Chess repo and building in VS (see build instructions). Let me know if you find this useful and I will include the Alpaca in the NuGet package in future releases.

There is a nice introduction to using Alpaca [here](http://www.eng.utah.edu/~cs5955/PPCP-Course-Material/ppcp/alpaca/Alpaca%20Introduction.pdf).
