### ISSUE TITLE
mcut returned with -667 exit code

### ISSUE THREAD

**Issue by pellared** [LeeSanderson/Chess#2]
When running `mcut runAllTests [path to your concurrency unit test assembly]` I am getting the following error:

> Test() (Context=, TestType=MChess): [Error]Invalid test result xml: The 'chessExitCode' attribute is invalid - The value '-667' is invalid according to its datatype 'http://research.microsoft.com/chess:exitCodeType' - The Enumeration constraint failed.

It happens for both your Concurrency project and one created by me from scratch,
Do you have any idea what could be wrong?

**Comment by LeeSanderson** [comment]
Running mcut from an administrative command prompt should solve this problem.

**Comment by ghost** [comment]
I've found this issue can also occur if the .NET Framework 2/3.x tooling is not installed.
