### ISSUE TITLE
Invalid test result xml

### ISSUE THREAD

**Issue by PocherninaElena** [LeeSanderson/Chess#3]
I'm running `mcut.exe` from administrator command prompt, but have the exception:

[Error]Invalid test result xml: The 'chessExitCode' attribute is invalid - The value '-667' is invalid according to its datatype 'http://research.microsoft.com/chess:exitCodeType' - The Enumeration constraint failed.

**Comment by LeeSanderson** [comment]
Elena,

This is a known issue. Running mcut from an administrative command prompt should solve this problem.

Lee

**Comment by PocherninaElena** [comment]
Lee,

But as I've written above I ran it from administrative command prompt.
