### ISSUE TITLE
mcut Abnormal temination

### ISSUE THREAD

**Issue by marty2013** [LeeSanderson/Chess#4]
Hi there
Apologies in advance if this issue hase been discussed previous - kick my lazy arse in the direction of that thread of it exists :-|
Running the following in cmd under admin...

_me>mcut runAllTests <unit test path...>\UnitTests.dll_

**Concurrency Unit Testing (MCUT) Console.
Copyright (C) Microsoft Corporation, 2010.
Running 1 tests with 1 test cases...
   1> Running test case TestConcurrency().
   1> Test result: Error
  1> TestConcurrency() (Context=, TestType=MChess): [Error]Abnormal termination (results corrupted)

Tests not passed:
  1> TestConcurrency() (Context=, TestType=MChess): [Error]Abnormal termination (results corrupted)

Test Cases Run: 1
   Passed Count: 0
   Inconclusive Count: 0
   Failed Count: 1

Finished running tests.**

TestConcurrncy is a shell method...
    [Test]
    [ScheduleTestMethod]
    public void TestTheTester()
    {
      // do nothing
    }

FYI - VS 2017 on Windows 10 under .NET 4.8
Please let me know if you need any more info.
Really appreciate your help in advance :-)

Martin

**Comment by LeeSanderson** [comment]
There are two known issues that may be causing this problem:

1. You need to run the mcut from an administrative command prompt
2. Some users have reported issues if the .NET 2/3.5 tooling has not been installed.

Let me know if this helps.

Lee

**Comment by marty2013** [comment]
Thanks very much Lee. I was running under admin but I will investigate point 2. :-)
Much appreciated.

**Comment by asgerhallas** [comment]
@marty2013 did you by any chance get it running? I'm having the same error message, and have tried both points too :)

**Comment by JosephYao** [comment]
I encountered the same issue even though I already got .NET 3.5 installed and ran it with admin privileges. Finally, I figured out a way to make it run. I need to install VS2013 with MFC and VS2015 with common tools for VC++ in addition. 

I have tried to install VS2013 and VS2015 redistribution pack for VC++, but I can't make it work.
